import Foundation

internal struct HTMLEntityDecoder {

    // WORKER: Populate this dictionary based on entities.c
    // This is a partial list. A full list would be generated by parsing entities.c
    private static let namedEntities: [String: String] = [
        "Aacute;": "\u{00C1}", // C: "\xC3\x81" - LATIN CAPITAL LETTER A WITH ACUTE
        "aacute;": "\u{00E1}", // C: "\xC3\xA1" - LATIN SMALL LETTER A WITH ACUTE
        "Acirc;": "\u{00C2}",  // C: "\xC3\x82" - LATIN CAPITAL LETTER A WITH CIRCUMFLEX
        "acirc;": "\u{00E2}",  // C: "\xC3\xA2" - LATIN SMALL LETTER A WITH CIRCUMFLEX
        "acute;": "\u{00B4}",  // C: "\xC2\xB4" - ACUTE ACCENT
        "AElig;": "\u{00C6}",  // C: "\xC3\x86" - LATIN CAPITAL LETTER AE
        "aelig;": "\u{00E6}",  // C: "\xC3\xA6" - LATIN SMALL LETTER AE
        "Agrave;": "\u{00C0}", // C: "\xC3\x80" - LATIN CAPITAL LETTER A WITH GRAVE
        "agrave;": "\u{00E0}", // C: "\xC3\xA0" - LATIN SMALL LETTER A WITH GRAVE
        "alefsym;": "\u{2135}",// C: "\xE2\x84\xB5" - ALEF SYMBOL
        "Alpha;": "\u{0391}",  // C: "\xCE\x91" - GREEK CAPITAL LETTER ALPHA
        "alpha;": "\u{03B1}",  // C: "\xCE\xB1" - GREEK SMALL LETTER ALPHA
        "amp;": "&",           // C: "&"        - AMPERSAND
        "and;": "\u{2227}",   // C: "\xE2\x88\xA7" - LOGICAL AND
        "ang;": "\u{2220}",   // C: "\xE2\x88\xA0" - ANGLE
        "Aring;": "\u{00C5}",  // C: "\xC3\x85" - LATIN CAPITAL LETTER A WITH RING ABOVE
        "aring;": "\u{00E5}",  // C: "\xC3\xA5" - LATIN SMALL LETTER A WITH RING ABOVE
        "asymp;": "\u{2248}",  // C: "\xE2\x89\x88" - ALMOST EQUAL TO
        "Atilde;": "\u{00C3}", // C: "\xC3\x83" - LATIN CAPITAL LETTER A WITH TILDE
        "atilde;": "\u{00E3}", // C: "\xC3\xA3" - LATIN SMALL LETTER A WITH TILDE
        "Auml;": "\u{00C4}",   // C: "\xC3\x84" - LATIN CAPITAL LETTER A WITH DIAERESIS
        "auml;": "\u{00E4}",   // C: "\xC3\xA4" - LATIN SMALL LETTER A WITH DIAERESIS
        "bdquo;": "\u{201E}",  // C: "\xE2\x80\x9E" - DOUBLE LOW-9 QUOTATION MARK
        "Beta;": "\u{0392}",   // C: "\xCE\x92" - GREEK CAPITAL LETTER BETA
        "beta;": "\u{03B2}",   // C: "\xCE\xB2" - GREEK SMALL LETTER BETA
        "brvbar;": "\u{00A6}", // C: "\xC2\xA6" - BROKEN BAR
        "bull;": "\u{2022}",  // C: "\xE2\x80\xA2" - BULLET
        "cap;": "\u{2229}",   // C: "\xE2\x88\xA9" - INTERSECTION
        "Ccedil;": "\u{00C7}", // C: "\xC3\x87" - LATIN CAPITAL LETTER C WITH CEDILLA
        "ccedil;": "\u{00E7}", // C: "\xC3\xA7" - LATIN SMALL LETTER C WITH CEDILLA
        "cedil;": "\u{00B8}",  // C: "\xC2\xB8" - CEDILLA
        "cent;": "\u{00A2}",   // C: "\xC2\xA2" - CENT SIGN
        "Chi;": "\u{03A7}",    // C: "\xCE\xA7" - GREEK CAPITAL LETTER CHI
        "chi;": "\u{03C7}",    // C: "\xCF\x87" - GREEK SMALL LETTER CHI
        "circ;": "\u{02C6}",   // C: "\xCB\x86" - MODIFIER LETTER CIRCUMFLEX ACCENT
        "clubs;": "\u{2663}",  // C: "\xE2\x99\xA3" - BLACK CLUB SUIT
        "cong;": "\u{2245}",   // C: "\xE2\x89\x85" - APPROXIMATELY EQUAL TO
        "copy;": "\u{00A9}",   // C: "\xC2\xA9" - COPYRIGHT SIGN
        "crarr;": "\u{21B5}",  // C: "\xE2\x86\xB5" - DOWNWARDS ARROW WITH CORNER LEFTWARDS
        "cup;": "\u{222A}",   // C: "\xE2\x88\xAA" - UNION
        "curren;": "\u{00A4}", // C: "\xC2\xA4" - CURRENCY SIGN
        "dagger;": "\u{2020}", // C: "\xE2\x80\xA0" - DAGGER
        "Dagger;": "\u{2021}", // C: "\xE2\x80\xA1" - DOUBLE DAGGER
        "darr;": "\u{2193}",   // C: "\xE2\x86\x93" - DOWNWARDS ARROW
        "dArr;": "\u{21D3}",   // C: "\xE2\x87\x93" - DOWNWARDS DOUBLE ARROW
        "deg;": "\u{00B0}",    // C: "\xC2\xB0" - DEGREE SIGN
        "Delta;": "\u{0394}",  // C: "\xCE\x94" - GREEK CAPITAL LETTER DELTA
        "delta;": "\u{03B4}",  // C: "\xCE\xB4" - GREEK SMALL LETTER DELTA
        "diams;": "\u{2666}",  // C: "\xE2\x99\xA6" - BLACK DIAMOND SUIT
        "divide;": "\u{00F7}", // C: "\xC3\xB7" - DIVISION SIGN
        "Eacute;": "\u{00C9}", // C: "\xC3\x89" - LATIN CAPITAL LETTER E WITH ACUTE
        "eacute;": "\u{00E9}", // C: "\xC3\xA9" - LATIN SMALL LETTER E WITH ACUTE
        "Ecirc;": "\u{00CA}",  // C: "\xC3\x8A" - LATIN CAPITAL LETTER E WITH CIRCUMFLEX
        "ecirc;": "\u{00EA}",  // C: "\xC3\xAA" - LATIN SMALL LETTER E WITH CIRCUMFLEX
        "Egrave;": "\u{00C8}", // C: "\xC3\x88" - LATIN CAPITAL LETTER E WITH GRAVE
        "egrave;": "\u{00E8}", // C: "\xC3\xA8" - LATIN SMALL LETTER E WITH GRAVE
        "empty;": "\u{2205}",  // C: "\xE2\x88\x85" - EMPTY SET
        "emsp;": "\u{2003}",   // C: "\xE2\x80\x83" - EM SPACE
        "ensp;": "\u{2002}",   // C: "\xE2\x80\x82" - EN SPACE
        "Epsilon;": "\u{0395}",// C: "\xCE\x95" - GREEK CAPITAL LETTER EPSILON
        "epsilon;": "\u{03B5}",// C: "\xCE\xB5" - GREEK SMALL LETTER EPSILON
        "equiv;": "\u{2261}",  // C: "\xE2\x89\xA1" - IDENTICAL TO
        "Eta;": "\u{0397}",    // C: "\xCE\x97" - GREEK CAPITAL LETTER ETA
        "eta;": "\u{03B7}",    // C: "\xCE\xB7" - GREEK SMALL LETTER ETA
        "ETH;": "\u{00D0}",    // C: "\xC3\x90" - LATIN CAPITAL LETTER ETH
        "eth;": "\u{00F0}",    // C: "\xC3\xB0" - LATIN SMALL LETTER ETH
        "Euml;": "\u{00CB}",   // C: "\xC3\x8B" - LATIN CAPITAL LETTER E WITH DIAERESIS
        "euml;": "\u{00EB}",   // C: "\xC3\xAB" - LATIN SMALL LETTER E WITH DIAERESIS
        "euro;": "\u{20AC}",   // C: "\xE2\x82\xAC" - EURO SIGN
        "exist;": "\u{2203}",  // C: "\xE2\x88\x83" - THERE EXISTS
        "fnof;": "\u{0192}",   // C: "\xC6\x92" - LATIN SMALL LETTER F WITH HOOK
        "forall;": "\u{2200}", // C: "\xE2\x88\x80" - FOR ALL
        "frac12;": "\u{00BD}", // C: "\xC2\xBD" - VULGAR FRACTION ONE HALF
        "frac14;": "\u{00BC}", // C: "\xC2\xBC" - VULGAR FRACTION ONE QUARTER
        "frac34;": "\u{00BE}", // C: "\xC2\xBE" - VULGAR FRACTION THREE QUARTERS
        "frasl;": "\u{2044}",  // C: "\xE2\x81\x84" - FRACTION SLASH
        "Gamma;": "\u{0393}",  // C: "\xCE\x93" - GREEK CAPITAL LETTER GAMMA
        "gamma;": "\u{03B3}",  // C: "\xCE\xB3" - GREEK SMALL LETTER GAMMA
        "ge;": "\u{2265}",    // C: "\xE2\x89\xA5" - GREATER-THAN OR EQUAL TO
        "gt;": ">",            // C: ">"        - GREATER-THAN SIGN
        "harr;": "\u{2194}",   // C: "\xE2\x86\x94" - LEFT RIGHT ARROW
        "hArr;": "\u{21D4}",   // C: "\xE2\x87\x94" - LEFT RIGHT DOUBLE ARROW
        "hearts;": "\u{2665}", // C: "\xE2\x99\xA5" - BLACK HEART SUIT
        "hellip;": "\u{2026}",// C: "\xE2\x80\xA6" - HORIZONTAL ELLIPSIS
        "Iacute;": "\u{00CD}", // C: "\xC3\x8D" - LATIN CAPITAL LETTER I WITH ACUTE
        "iacute;": "\u{00ED}", // C: "\xC3\xAD" - LATIN SMALL LETTER I WITH ACUTE
        "Icirc;": "\u{00CE}",  // C: "\xC3\x8E" - LATIN CAPITAL LETTER I WITH CIRCUMFLEX
        "icirc;": "\u{00EE}",  // C: "\xC3\xAE" - LATIN SMALL LETTER I WITH CIRCUMFLEX
        "iexcl;": "\u{00A1}",  // C: "\xC2\xA1" - INVERTED EXCLAMATION MARK
        "Igrave;": "\u{00CC}", // C: "\xC3\x8C" - LATIN CAPITAL LETTER I WITH GRAVE
        "igrave;": "\u{00EC}", // C: "\xC3\xAC" - LATIN SMALL LETTER I WITH GRAVE
        "image;": "\u{2111}",  // C: "\xE2\x84\x91" - BLACK-LETTER CAPITAL I
        "infin;": "\u{221E}",  // C: "\xE2\x88\x9E" - INFINITY
        "int;": "\u{222B}",   // C: "\xE2\x88\xAB" - INTEGRAL
        "Iota;": "\u{0399}",   // C: "\xCE\x99" - GREEK CAPITAL LETTER IOTA
        "iota;": "\u{03B9}",   // C: "\xCE\xB9" - GREEK SMALL LETTER IOTA
        "iquest;": "\u{00BF}", // C: "\xC2\xBF" - INVERTED QUESTION MARK
        "isin;": "\u{2208}",   // C: "\xE2\x88\x88" - ELEMENT OF
        "Iuml;": "\u{00CF}",   // C: "\xC3\x8F" - LATIN CAPITAL LETTER I WITH DIAERESIS
        "iuml;": "\u{00EF}",   // C: "\xC3\xAF" - LATIN SMALL LETTER I WITH DIAERESIS
        "Kappa;": "\u{039A}",  // C: "\xCE\x9A" - GREEK CAPITAL LETTER KAPPA
        "kappa;": "\u{03BA}",  // C: "\xCE\xBA" - GREEK SMALL LETTER KAPPA
        "Lambda;": "\u{039B}", // C: "\xCE\x9B" - GREEK CAPITAL LETTER LAMDA
        "lambda;": "\u{03BB}", // C: "\xCE\xBB" - GREEK SMALL LETTER LAMDA
        "lang;": "\u{27E8}",   // C: "\xE2\x9F\xA8" - MATHEMATICAL LEFT ANGLE BRACKET
        "laquo;": "\u{00AB}",  // C: "\xC2\xAB" - LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        "larr;": "\u{2190}",   // C: "\xE2\x86\x90" - LEFTWARDS ARROW
        "lArr;": "\u{21D0}",   // C: "\xE2\x87\x90" - LEFTWARDS DOUBLE ARROW
        "lceil;": "\u{2308}",  // C: "\xE2\x8C\x88" - LEFT CEILING
        "ldquo;": "\u{201C}",  // C: "\xE2\x80\x9C" - LEFT DOUBLE QUOTATION MARK
        "le;": "\u{2264}",    // C: "\xE2\x89\xA4" - LESS-THAN OR EQUAL TO
        "lfloor;": "\u{230A}", // C: "\xE2\x8C\x8A" - LEFT FLOOR
        "lowast;": "\u{2217}", // C: "\xE2\x88\x97" - ASTERISK OPERATOR
        "loz;": "\u{25CA}",   // C: "\xE2\x97\x8A" - LOZENGE
        "lrm;": "\u{200E}",   // C: "\xE2\x80\x8E" - LEFT-TO-RIGHT MARK
        "lsaquo;": "\u{2039}", // C: "\xE2\x80\xB9" - SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        "lsquo;": "\u{2018}",  // C: "\xE2\x80\x98" - LEFT SINGLE QUOTATION MARK
        "lt;": "<",            // C: "<"        - LESS-THAN SIGN
        "macr;": "\u{00AF}",   // C: "\xC2\xAF" - MACRON
        "mdash;": "\u{2014}",  // C: "\xE2\x80\x94" - EM DASH
        "micro;": "\u{00B5}",  // C: "\xC2\xB5" - MICRO SIGN
        "middot;": "\u{00B7}", // C: "\xC2\xB7" - MIDDLE DOT
        "minus;": "\u{2212}",  // C: "\xE2\x88\x92" - MINUS SIGN
        "Mu;": "\u{039C}",     // C: "\xCE\x9C" - GREEK CAPITAL LETTER MU
        "mu;": "\u{03BC}",     // C: "\xCE\xBC" - GREEK SMALL LETTER MU
        "nabla;": "\u{2207}",  // C: "\xE2\x88\x87" - NABLA
        "nbsp;": "\u{00A0}",   // C: "\xC2\xA0" - NO-BREAK SPACE
        "ndash;": "\u{2013}",  // C: "\xE2\x80\x93" - EN DASH
        "ne;": "\u{2260}",    // C: "\xE2\x89\xA0" - NOT EQUAL TO
        "ni;": "\u{220B}",    // C: "\xE2\x88\x8B" - CONTAINS AS MEMBER
        "not;": "\u{00AC}",    // C: "\xC2\xAC" - NOT SIGN
        "notin;": "\u{2209}",  // C: "\xE2\x88\x89" - NOT AN ELEMENT OF
        "nsub;": "\u{2284}",   // C: "\xE2\x8A\x84" - NOT A SUBSET OF
        "Ntilde;": "\u{00D1}", // C: "\xC3\x91" - LATIN CAPITAL LETTER N WITH TILDE
        "ntilde;": "\u{00F1}", // C: "\xC3\xB1" - LATIN SMALL LETTER N WITH TILDE
        "Nu;": "\u{039D}",     // C: "\xCE\x9D" - GREEK CAPITAL LETTER NU
        "nu;": "\u{03BD}",     // C: "\xCE\xBD" - GREEK SMALL LETTER NU
        "Oacute;": "\u{00D3}", // C: "\xC3\x93" - LATIN CAPITAL LETTER O WITH ACUTE
        "oacute;": "\u{00F3}", // C: "\xC3\xB3" - LATIN SMALL LETTER O WITH ACUTE
        "Ocirc;": "\u{00D4}",  // C: "\xC3\x94" - LATIN CAPITAL LETTER O WITH CIRCUMFLEX
        "ocirc;": "\u{00F4}",  // C: "\xC3\xB4" - LATIN SMALL LETTER O WITH CIRCUMFLEX
        "OElig;": "\u{0152}",  // C: "\xC5\x92" - LATIN CAPITAL LIGATURE OE
        "oelig;": "\u{0153}",  // C: "\xC5\x93" - LATIN SMALL LIGATURE OE
        "Ograve;": "\u{00D2}", // C: "\xC3\x92" - LATIN CAPITAL LETTER O WITH GRAVE
        "ograve;": "\u{00F2}", // C: "\xC3\xB2" - LATIN SMALL LETTER O WITH GRAVE
        "oline;": "\u{203E}",  // C: "\xE2\x80\xBE" - OVERLINE
        "Omega;": "\u{03A9}",  // C: "\xCE\xA9" - GREEK CAPITAL LETTER OMEGA
        "omega;": "\u{03C9}",  // C: "\xCF\x89" - GREEK SMALL LETTER OMEGA
        "Omicron;": "\u{039F}",// C: "\xCE\x9F" - GREEK CAPITAL LETTER OMICRON
        "omicron;": "\u{03BF}",// C: "\xCE\xBF" - GREEK SMALL LETTER OMICRON
        "oplus;": "\u{2295}",  // C: "\xE2\x8A\x95" - CIRCLED PLUS
        "or;": "\u{2228}",    // C: "\xE2\x88\xA8" - LOGICAL OR
        "ordf;": "\u{00AA}",   // C: "\xC2\xAA" - FEMININE ORDINAL INDICATOR
        "ordm;": "\u{00BA}",   // C: "\xC2\xBA" - MASCULINE ORDINAL INDICATOR
        "Oslash;": "\u{00D8}", // C: "\xC3\x98" - LATIN CAPITAL LETTER O WITH STROKE
        "oslash;": "\u{00F8}", // C: "\xC3\xB8" - LATIN SMALL LETTER O WITH STROKE
        "Otilde;": "\u{00D5}", // C: "\xC3\x95" - LATIN CAPITAL LETTER O WITH TILDE
        "otilde;": "\u{00F5}", // C: "\xC3\xB5" - LATIN SMALL LETTER O WITH TILDE
        "otimes;": "\u{2297}", // C: "\xE2\x8A\x97" - CIRCLED TIMES
        "Ouml;": "\u{00D6}",   // C: "\xC3\x96" - LATIN CAPITAL LETTER O WITH DIAERESIS
        "ouml;": "\u{00F6}",   // C: "\xC3\xB6" - LATIN SMALL LETTER O WITH DIAERESIS
        "para;": "\u{00B6}",   // C: "\xC2\xB6" - PILCROW SIGN
        "part;": "\u{2202}",   // C: "\xE2\x88\x82" - PARTIAL DIFFERENTIAL
        "permil;": "\u{2030}", // C: "\xE2\x80\xB0" - PER MILLE SIGN
        "perp;": "\u{22A5}",   // C: "\xE2\x8A\xA5" - UP TACK
        "Phi;": "\u{03A6}",    // C: "\xCE\xA6" - GREEK CAPITAL LETTER PHI
        "phi;": "\u{03C6}",    // C: "\xCF\x86" - GREEK SMALL LETTER PHI
        "Pi;": "\u{03A0}",     // C: "\xCE\xA0" - GREEK CAPITAL LETTER PI
        "pi;": "\u{03C0}",     // C: "\xCF\x80" - GREEK SMALL LETTER PI
        "piv;": "\u{03D6}",    // C: "\xCF\x96" - GREEK PI SYMBOL
        "plusmn;": "\u{00B1}", // C: "\xC2\xB1" - PLUS-MINUS SIGN
        "pound;": "\u{00A3}",  // C: "\xC2\xA3" - POUND SIGN
        "prime;": "\u{2032}",  // C: "\xE2\x80\xB2" - PRIME
        "Prime;": "\u{2033}",  // C: "\xE2\x80\xB3" - DOUBLE PRIME
        "prod;": "\u{220F}",   // C: "\xE2\x88\x8F" - N-ARY PRODUCT
        "prop;": "\u{221D}",   // C: "\xE2\x88\x9D" - PROPORTIONAL TO
        "Psi;": "\u{03A8}",    // C: "\xCE\xA8" - GREEK CAPITAL LETTER PSI
        "psi;": "\u{03C8}",    // C: "\xCF\x88" - GREEK SMALL LETTER PSI
        "quot;": "\"",         // C: "\""       - QUOTATION MARK
        "radic;": "\u{221A}",  // C: "\xE2\x88\x9A" - SQUARE ROOT
        "rang;": "\u{27E9}",   // C: "\xE2\x9F\xA9" - MATHEMATICAL RIGHT ANGLE BRACKET
        "raquo;": "\u{00BB}",  // C: "\xC2\xBB" - RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        "rarr;": "\u{2192}",   // C: "\xE2\x86\x92" - RIGHTWARDS ARROW
        "rArr;": "\u{21D2}",   // C: "\xE2\x87\x92" - RIGHTWARDS DOUBLE ARROW
        "rceil;": "\u{2309}",  // C: "\xE2\x8C\x89" - RIGHT CEILING
        "rdquo;": "\u{201D}",  // C: "\xE2\x80\x9D" - RIGHT DOUBLE QUOTATION MARK
        "real;": "\u{211C}",   // C: "\xE2\x84\x9C" - BLACK-LETTER CAPITAL R
        "reg;": "\u{00AE}",    // C: "\xC2\xAE" - REGISTERED SIGN
        "rfloor;": "\u{230B}", // C: "\xE2\x8C\x8B" - RIGHT FLOOR
        "Rho;": "\u{03A1}",    // C: "\xCE\xA1" - GREEK CAPITAL LETTER RHO
        "rho;": "\u{03C1}",    // C: "\xCF\x81" - GREEK SMALL LETTER RHO
        "rlm;": "\u{200F}",   // C: "\xE2\x80\x8F" - RIGHT-TO-LEFT MARK
        "rsaquo;": "\u{203A}", // C: "\xE2\x80\xBA" - SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        "rsquo;": "\u{2019}",  // C: "\xE2\x80\x99" - RIGHT SINGLE QUOTATION MARK
        "sbquo;": "\u{201A}",  // C: "\xE2\x80\x9A" - SINGLE LOW-9 QUOTATION MARK
        "Scaron;": "\u{0160}", // C: "\xC5\xA0" - LATIN CAPITAL LETTER S WITH CARON
        "scaron;": "\u{0161}", // C: "\xC5\xA1" - LATIN SMALL LETTER S WITH CARON
        "sdot;": "\u{22C5}",   // C: "\xE2\x8B\x85" - DOT OPERATOR
        "sect;": "\u{00A7}",   // C: "\xC2\xA7" - SECTION SIGN
        "shy;": "\u{00AD}",    // C: "\xC2\xAD" - SOFT HYPHEN
        "Sigma;": "\u{03A3}",  // C: "\xCE\xA3" - GREEK CAPITAL LETTER SIGMA
        "sigma;": "\u{03C3}",  // C: "\xCF\x83" - GREEK SMALL LETTER SIGMA
        "sigmaf;": "\u{03C2}", // C: "\xCF\x82" - GREEK SMALL LETTER FINAL SIGMA
        "sim;": "\u{223C}",   // C: "\xE2\x88\xBC" - TILDE OPERATOR
        "spades;": "\u{2660}", // C: "\xE2\x99\xA0" - BLACK SPADE SUIT
        "sub;": "\u{2282}",   // C: "\xE2\x8A\x82" - SUBSET OF
        "sube;": "\u{2286}",   // C: "\xE2\x8A\x86" - SUBSET OF OR EQUAL TO
        "sum;": "\u{2211}",   // C: "\xE2\x88\x91" - N-ARY SUMMATION
        "sup;": "\u{2283}",   // C: "\xE2\x8A\x83" - SUPERSET OF
        "supe;": "\u{2287}",   // C: "\xE2\x8A\x87" - SUPERSET OF OR EQUAL TO
        "szlig;": "\u{00DF}",  // C: "\xC3\x9F" - LATIN SMALL LETTER SHARP S
        "Tau;": "\u{03A4}",    // C: "\xCE\xA4" - GREEK CAPITAL LETTER TAU
        "tau;": "\u{03C4}",    // C: "\xCF\x84" - GREEK SMALL LETTER TAU
        "there4;": "\u{2234}", // C: "\xE2\x88\xB4" - THEREFORE
        "Theta;": "\u{0398}",  // C: "\xCE\x98" - GREEK CAPITAL LETTER THETA
        "theta;": "\u{03B8}",  // C: "\xCE\xB8" - GREEK SMALL LETTER THETA
        "thetasym;": "\u{03D1}",// C: "\xCF\x91" - GREEK THETA SYMBOL
        "thinsp;": "\u{2009}", // C: "\xE2\x80\x89" - THIN SPACE
        "THORN;": "\u{00DE}",  // C: "\xC3\x9E" - LATIN CAPITAL LETTER THORN
        "thorn;": "\u{00FE}",  // C: "\xC3\xBE" - LATIN SMALL LETTER THORN
        "tilde;": "\u{02DC}",   // C: "\xCB\x9C" - SMALL TILDE
        "times;": "\u{00D7}",  // C: "\xC3\x97" - MULTIPLICATION SIGN
        "trade;": "\u{2122}",  // C: "\xE2\x84\xA2" - TRADE MARK SIGN
        "Uacute;": "\u{00DA}", // C: "\xC3\x9A" - LATIN CAPITAL LETTER U WITH ACUTE
        "uacute;": "\u{00FA}", // C: "\xC3\xBA" - LATIN SMALL LETTER U WITH ACUTE
        "uarr;": "\u{2191}",   // C: "\xE2\x86\x91" - UPWARDS ARROW
        "uArr;": "\u{21D1}",   // C: "\xE2\x87\x91" - UPWARDS DOUBLE ARROW
        "Ucirc;": "\u{00DB}",  // C: "\xC3\x9B" - LATIN CAPITAL LETTER U WITH CIRCUMFLEX
        "ucirc;": "\u{00FB}",  // C: "\xC3\xBB" - LATIN SMALL LETTER U WITH CIRCUMFLEX
        "Ugrave;": "\u{00D9}", // C: "\xC3\x99" - LATIN CAPITAL LETTER U WITH GRAVE
        "ugrave;": "\u{00F9}", // C: "\xC3\xB9" - LATIN SMALL LETTER U WITH GRAVE
        "uml;": "\u{00A8}",    // C: "\xC2\xA8" - DIAERESIS
        "upsih;": "\u{03D2}",  // C: "\xCF\x92" - GREEK UPSILON WITH HOOK SYMBOL
        "Upsilon;": "\u{03A5}",// C: "\xCE\xA5" - GREEK CAPITAL LETTER UPSILON
        "upsilon;": "\u{03C5}",// C: "\xCF\x85" - GREEK SMALL LETTER UPSILON
        "Uuml;": "\u{00DC}",   // C: "\xC3\x9C" - LATIN CAPITAL LETTER U WITH DIAERESIS
        "uuml;": "\u{00FC}",   // C: "\xC3\xBC" - LATIN SMALL LETTER U WITH DIAERESIS
        "weierp;": "\u{2118}", // C: "\xE2\x84\x98" - SCRIPT CAPITAL P
        "Xi;": "\u{039E}",     // C: "\xCE\x9E" - GREEK CAPITAL LETTER XI
        "xi;": "\u{03BE}",     // C: "\xCE\xBE" - GREEK SMALL LETTER XI
        "Yacute;": "\u{00DD}", // C: "\xC3\x9D" - LATIN CAPITAL LETTER Y WITH ACUTE
        "yacute;": "\u{00FD}", // C: "\xC3\xBD" - LATIN SMALL LETTER Y WITH ACUTE
        "yen;": "\u{00A5}",    // C: "\xC2\xA5" - YEN SIGN
        "yuml;": "\u{00FF}",   // C: "\xC3\xBF" - LATIN SMALL LETTER Y WITH DIAERESIS
        "Yuml;": "\u{0178}",   // C: "\xC5\xB8" - LATIN CAPITAL LETTER Y WITH DIAERESIS
        "Zeta;": "\u{0396}",   // C: "\xCE\x96" - GREEK CAPITAL LETTER ZETA
        "zeta;": "\u{03B6}",   // C: "\xCE\xB6" - GREEK SMALL LETTER ZETA
        "zwj;": "\u{200D}",   // C: "\xE2\x80\x8D" - ZERO WIDTH JOINER
        "zwnj;": "\u{200C}"   // C: "\xE2\x80\x8C" - ZERO WIDTH NON-JOINER
    ]

    internal static func decode(_ html: String) -> String {
        var result = String()
        // Pre-allocate capacity for the result string.
        // Using html.utf16.count as a heuristic, as HTML entities often expand or contract.
        // This is an optimization and not strictly necessary for correctness.
        result.reserveCapacity(html.utf16.count) 

        var currentIndex = html.startIndex
        let endIndex = html.endIndex

        while currentIndex < endIndex {
            // Find the next ampersand
            guard let ampersandIndex = html[currentIndex...].firstIndex(of: "&") else {
                // No more ampersands, append the rest of the string and break
                result.append(contentsOf: html[currentIndex...])
                break
            }

            // Append the text before the ampersand
            result.append(contentsOf: html[currentIndex..<ampersandIndex])
            
            // Move current index to the ampersand
            currentIndex = ampersandIndex

            // Find the corresponding semicolon
            guard let semicolonIndex = html[currentIndex...].firstIndex(of: ";") else {
                // No semicolon found after ampersand, treat '&' as literal
                result.append("&") 
                currentIndex = html.index(after: currentIndex) // Move past the '&'
                continue
            }
            
            // Potential entity is between ampersandIndex (exclusive) and semicolonIndex (inclusive)
            let entityStartIndex = html.index(after: currentIndex)

            // Check for invalid entities like "&;" or cases where entityStartIndex might be beyond semicolonIndex
            if entityStartIndex > semicolonIndex { 
                 result.append(contentsOf: html[currentIndex...semicolonIndex]) // Append the original malformed segment
                 currentIndex = html.index(after: semicolonIndex)
                 continue
            }
            
            // Extract the content of the entity (e.g., "amp" or "#123" or "#xABC")
            // entityKey includes the semicolon for named entities lookup, entityContent does not.
            let entityKey = String(html[entityStartIndex...semicolonIndex]) 
            let entityContent = String(html[entityStartIndex..<semicolonIndex]) 
            
            if entityContent.hasPrefix("#") {
                // Numeric entity
                let numberString = String(entityContent.dropFirst()) // Remove '#'
                var code: UInt32?

                if numberString.lowercased().hasPrefix("x") {
                    // Hexadecimal
                    code = UInt32(String(numberString.dropFirst()), radix: 16) // Remove 'x'
                } else {
                    // Decimal
                    code = UInt32(numberString, radix: 10)
                }

                if let c = code, c != 0, let scalar = UnicodeScalar(c) { // Disallow NULL bytes (c != 0)
                    result.append(String(scalar))
                } else {
                    // Invalid numeric entity, append original text
                    result.append(contentsOf: html[currentIndex...semicolonIndex])
                }
            } else if let decoded = namedEntities[entityKey] {
                // Named entity
                result.append(decoded)
            } else {
                // Unknown named entity, append original text
                result.append(contentsOf: html[currentIndex...semicolonIndex])
            }

            // Move current index past the semicolon
            currentIndex = html.index(after: semicolonIndex)
        }
        return result
    }
}
// Test cases (can be moved to a test file later)
/*
print(HTMLEntityDecoder.decode("Hello &amp; &gt; &lt; &quot; &nbsp; &copy; &reg; world"))
// Expected: Hello & > < "   © ® world
print(HTMLEntityDecoder.decode("Test: &eacute; &Eacute; &euro; &emsp;"))
// Expected: Test: é É €  
print(HTMLEntityDecoder.decode("Numeric: &#65; &#x41;"))
// Expected: Numeric: A A
print(HTMLEntityDecoder.decode("Invalid: &unknown; &#; &#x; &#0; &amp"))
// Expected: Invalid: &unknown; &#; &#x; &#0; &amp
print(HTMLEntityDecoder.decode("Edge case: &; testing"))
// Expected: &; testing
print(HTMLEntityDecoder.decode("Ends with ampersand: test&"))
// Expected: Ends with ampersand: test&
print(HTMLEntityDecoder.decode("Ends with partial entity: test&am"))
// Expected: Ends with partial entity: test&am
print(HTMLEntityDecoder.decode("No entities here."))
// Expected: No entities here.
print(HTMLEntityDecoder.decode("&amp;&amp;"))
// Expected: &&
print(HTMLEntityDecoder.decode("&#123;&copy;&#xABC;")) // { © ª (assuming #xABC is a valid char)
// Expected: {©ª (actually  किरदार, U+0ABC is DEVANAGARI SIGN INVERTED CANDRABINDU) -> {© किरदार
*/
